/**
 * Speedray Authentication API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as querystring from "querystring";
import * as url from "url";

import * as isomorphicFetch from "isomorphic-fetch";
import * as assign from "core-js/library/fn/object/assign";

interface Dictionary<T> { [index: string]: T; }
export interface FetchAPI { (url: string, init?: any): Promise<any>; }

const BASE_PATH = "http://192.168.1.23:8080/o/rest/speedray/api/v1";

export interface FetchArgs {
    url: string;
    options: any; 
}

export class BaseAPI {
    basePath: string;
    fetch: FetchAPI;

    constructor(fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) {
        this.basePath = basePath;
        this.fetch = fetch;
    }
}

/**
 * Request payload for Authentication call
 */
export interface AuthenticationRequest {
    "type": AuthenticationRequestTypeEnum;
    "id": string;
    "password": string;
}

export type AuthenticationRequestTypeEnum = "SCREEN" | "EMAIL" | "ID";
/**
 * Response payload for Authentication call
 */
export interface AuthenticationResponse {
    "responseStatus"?: AuthenticationResponseResponseStatusEnum;
    "generatedToken"?: string;
}

export type AuthenticationResponseResponseStatusEnum = "SUCCESS" | "SUCCESS_CHANGE_PASSWORD_REQUIRED" | "SYSTEM_UNAVAILABLE" | "INTERNAL_ERROR" | "INVALID_CREDENTIALS";


/**
 * DefaultApi - fetch parameter creator
 */
export const DefaultApiFetchParamCreactor = {
    /** 
     * Signin and return token
     * @param auth Authentication payload
     */
    authenticate(params: {  auth: AuthenticationRequest; }): FetchArgs {
        // verify required parameter "auth" is set
        if (params["auth"] == null) {
            throw new Error("Missing required parameter auth when calling authenticate");
        }
        const baseUrl = `/security/authenticate`;
        let urlObj = url.parse(baseUrl, true);
        let fetchOptions: RequestInit = { method: "POST" };

        let contentTypeHeader: Dictionary<string>;
        contentTypeHeader = { "Content-Type": "application/json" };
        if (params["auth"]) {
            fetchOptions.body = JSON.stringify(params["auth"] || {});
        }
        if (contentTypeHeader) {
            fetchOptions.headers = contentTypeHeader;
        }
        return {
            url: url.format(urlObj),
            options: fetchOptions,
        };
    },
}

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = {
    /** 
     * Signin and return token
     * @param auth Authentication payload
     */
    authenticate(params: { auth: AuthenticationRequest;  }): (fetch: FetchAPI, basePath?: string) => Promise<AuthenticationResponse> {
        const fetchArgs = DefaultApiFetchParamCreactor.authenticate(params);
        return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
            return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return response.json();
                } else {
                    throw response;
                }
            });
        };
    },
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /** 
     * Signin and return token
     * @param auth Authentication payload
     */
    authenticate(params: {  auth: AuthenticationRequest; }) {
        return DefaultApiFp.authenticate(params)(this.fetch, this.basePath);
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (fetch?: FetchAPI, basePath?: string) {
    return {
        /** 
         * Signin and return token
         * @param auth Authentication payload
         */
        authenticate(params: {  auth: AuthenticationRequest; }) {
            return DefaultApiFp.authenticate(params)(fetch, basePath);
        },
    }
};

